name: CI

on: [push, pull_request]

jobs:
  lint-black:
    name: Black code formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install python venv
        run: sudo apt-get -y install python3.12-venv

      - name: formatter
        uses: psf/black@stable
        with:
          src: "."
          options: "--diff"

  test-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
      - name: Test with flake8
        run: |
          python -m flake8

  unittests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pytest
      - name: Test with pytest
        run: |
          pytest